server:
  port: 8080
spring:
  #数据库配置  start
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/security-demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: 12345678
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        enabled: true   #默认值为true，即打开监控页面，但存在泄漏信息的风险，所以修改为false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  #数据库配置  end
  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/com.yisu.oauth2.db.mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
fw:
  worker:
    workerId: 10
    dataCenterId: 10
  security:
    oauth:
      jwtSigningKey: security
      clients[0]:
        clientId: test1
        clientSecret: test1
      clients[1]:
        clientId: test2
        clientSecret: test2
    oauth2:
      storeType: redis  # 还可以设置jwt

logging:
  level:
    com.yisu: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS