#本节说的是springboot的默认配置
server:
  port: 8080  #应用端口号
logging:
  com.yisu: debug #日志级别
spring:
  security:
    user:
      name: user  #自定义这是用户名，如果没设置 默认的用户名是user
      password: 123456 #自定义密码，如果没设置 默认的密码在控制台中寻找
